import Head from 'next/head';
import dark from '../styles/Themes/dark';
import light from '../styles/Themes/light';
import { ThemeProvider } from 'styled-components';
import React, { useEffect, useState } from 'react';
import { Footer } from '../components/footer/Footer';
import { Header } from '../components/header/Header';
import Cookie, { CookieAttributes } from 'js-cookie';
import { parseCookies } from '../libs/parseCookies';
import { Content } from '../components/content/Content';
import type { NextPage, GetServerSideProps } from 'next';
import { GlobalStyle } from '../styles/Global';

const Home: NextPage<CookieAttributes> = ({ themeValue }) => {
  const [ theme, setTheme ] = useState(() => JSON.parse(themeValue))
    
  useEffect(() => {
    Cookie.set('changedTheme', JSON.stringify(theme))
  }, [theme])

  const toggleTheme = () => theme.title === 'light' ? setTheme(dark) : setTheme(light)

  return (
    <div>
      <Head>
        <title>Dark Theme</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <ThemeProvider theme={theme}>
        <div>
            <GlobalStyle />
            <Header />
            <Content toggleTheme={toggleTheme} />
            <Footer />
        </div>  
      </ThemeProvider>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const cookies = parseCookies(req);
  return {
    props: {
      themeValue: cookies.changedTheme
    }
  }
}

export default Home;


