import Head from 'next/head';
import dark from '../styles/Themes/dark';
import light from '../styles/Themes/light';
import { ThemeProvider } from 'styled-components';
import React, { useEffect, useState } from 'react';
import { Footer } from '../components/footer/Footer';
import { Header } from '../components/header/Header';
import { Content } from '../components/content/Content';
import type { NextPage } from 'next';
import { GlobalStyle } from '../styles/Global';

interface ServerProps {
    themeValue: string;
}

const Home: NextPage = () => {
  const [ theme, setTheme ] = useState(light);

  const toggleTheme = () => theme.title === 'light' ? setTheme(dark) : setTheme(light)

  return (
    <div>
      <Head>
        <title>Dark Theme</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <ThemeProvider theme={theme}>
        <div>
            <GlobalStyle />
            <Header />
            <Content toggleTheme={toggleTheme} />
            <Footer />
        </div>  
      </ThemeProvider>
    </div>
  )
}

export default Home;


